#34 Change status value to boolean
ArunBohra12/natours-backend pull request #37
Opened 2023-09-02 19:44 UTC by LogaMithran

Boolean gives much more clarity and code readablity

Tests
{
    "status": true,
    "message": "User created successfully",
    "data": {}
}
{
    "status": false,
    "type": "fail",
    "error": {
        "index": 0,
        "code": 11000,
        "keyPattern": {
            "email": 1
        },
        "keyValue": {
            "email": "user-1@gmail.com"
        },
        "statusCode": 500,
        "status": false,
        "type": "fail"
    }
}

2023-09-02 21:01 UTC, ArunBohra12 requested changes
Can you please add this change?

2023-09-02 21:01 UTC, ArunBohra12 commented on app/utils/imageUpload.js
> +    return [false, new AppError('Unable upload image. Please try again.', 401)];
@LogaMithran, can you please check here, `app/controllers/userController.js:31`

we use the following still and it isn't updated yet
```js
const data = await uploadProfileImage(req.file, fileName, next);

if (data[0] === 0) {
  return next(data[1]);
}
```

2023-09-03 03:33 UTC, LogaMithran commented on app/utils/imageUpload.js
> +    return [false, new AppError('Unable upload image. Please try again.', 401)];
@ArunBohra12 Now I have updated it

2023-09-03 04:05 UTC, ArunBohra12 commented on app/utils/imageUpload.js
> +    return [false, new AppError('Unable upload image. Please try again.', 401)];
Earlier, we wrote the condition as `data[0] === 0`, now we need to check if it is false so I added `!data[0]` the exclamation (to run condition if it is false) 😉.

2023-09-03 04:06 UTC, ArunBohra12 approved these changes
Looks good now 🔥🔥

2023-09-03 04:06 UTC, merged